name: Generate Directory Markdown

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Create new branch
        env:
          BRANCH_NAME: update-directory-md-${{ github.run_id }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b $BRANCH_NAME

      - name: Clone Directory Generator
        run: |
          git clone https://github.com/DenizAltunkapan/directory-tree-generator.git tools/dtg
          node tools/dtg/src/index.js --path src --extensions .java

      - name: Show changes (debug)
        run: git diff || echo "No changes"

      - name: Commit and push
        env:
          BRANCH_NAME: update-directory-md-${{ github.run_id }}
        run: |
          git add DIRECTORY.md
          git commit -m "chore: update DIRECTORY.md" || echo "Nothing to commit"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-directory-md-${{ github.run_id }}
          title: "Update DIRECTORY.md"
          body: |
            This pull request updates the `DIRECTORY.md` file automatically.
          base: master
